# Generated by Django 3.2 on 2021-04-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=50, verbose_name='Животное')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Кличка')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_posted', models.DateField(verbose_name='Дата подачи объявления')),
                ('photo', models.ImageField(null=True, upload_to='uploads/photos/', verbose_name='Фото')),
            ],
        ),
    ]
