# Generated by Django 3.2 on 2021-04-20 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['date_posted']},
        ),
    ]
