# Generated by Django 3.2 on 2021-04-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_pet_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(null=True, upload_to='uploads/photos', verbose_name='Фото'),
        ),
    ]
